package bingbong;

import java.io.File;

import bingbong.command.Command;
import bingbong.exception.BingBongException;
import bingbong.parser.Parser;
import bingbong.storage.Storage;
import bingbong.task.TaskList;
import bingbong.ui.Ui;

/**
 * Main class that controls the chatbot. It connects the UI, storage, and task list together to run the program.
 */
public class BingBong {

    private final Ui ui;
    private final Storage storage;
    private final TaskList tasks;

    /**
     * Initializes a new instance of the BingBong chatbot engine.
     */
    public BingBong() {
        this.ui = new Ui();
        this.storage = new Storage("." + File.separator + "data" + File.separator + "bingbong.txt");
        this.tasks = new TaskList(storage.load());
    }

    public static void main(String[] args) {
        new BingBong().run();
    }

    /**
     * Executes the core operation sequence for the chatbot.
     */
    public void run() {
        ui.showWelcome();
        boolean isExit = false;

        while (!isExit) {
            String input = ui.readCommand();
            try {
                Command command = Parser.parse(input);
                ui.showHLine();
                command.execute(tasks, ui, storage);
                isExit = command.isExit();
            } catch (BingBongException e) {
                ui.showHLine();
                ui.print(e.getMessage());
            } catch (NumberFormatException e) {
                ui.showHLine();
                ui.print("Please enter a valid number! :(");
            }
            ui.showHLine();
        }
    }

    /**
     * Intercepts and returns the text response for a given user command input to be displayed in the GUI.
     *
     * @param input The raw command line entered by the user in the text box.
     * @return The text output generated by executing the command.
     */
    public String getResponse(String input) {
        StringBuilder outputBuffer = new StringBuilder();
        Ui interceptorUi = new Ui() {
            @Override
            public void print(String message) {
                outputBuffer.append(message).append("\n");
            }

            @Override
            public void showWelcome() {
            }

            @Override
            public void showHLine() {
            }
        };

        try {
            Command command = Parser.parse(input);
            command.execute(tasks, interceptorUi, storage);
            return outputBuffer.toString().trim();
        } catch (BingBongException e) {
            return e.getMessage();
        } catch (NumberFormatException e) {
            return "Please enter a valid number! :(";
        }
    }

    /**
     * Generates the initial welcome greeting message for the GUI interface.
     *
     * @return The standard welcome string sequence.
     */
    public String getGreeting() {
        return "BingBong!\nWhat can I do for you today? :D";
    }

}
